management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

  opentelemetry:
    resource-attributes:
      service.name: ${OTEL_SERVICE_NAME:forward-service-mvc}
      service.namespace: ${OTEL_SERVICE_NAMESPACE:default}

  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
        step: ${OTEL_METRIC_EXPORT_INTERVAL:60s}
        read-timeout: ${OTEL_METRIC_EXPORT_TIMEOUT:10s}


spring:
  application:
    name: forward-service-mvc
