{
 "title": "JVM (Micrometer)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(process_uptime_milliseconds)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{k8s_pod_name=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{k8s_pod_name=\"$pod\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{k8s_pod_name=\"$pod\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime_milliseconds{k8s_pod_name=\"$pod\"}/1000)"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_milliseconds{k8s_pod_name=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{k8s_pod_name=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{k8s_pod_name=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{k8s_pod_name=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{k8s_pod_name=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_pod_name=\"$pod\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{k8s_pod_name=\"$pod\", http_response_status_code=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{k8s_pod_name=\"$pod\", http_response_status_code!~\"5..\"}[1m]))/sum(rate(http_server_request_duration_seconds_count{k8s_pod_name=\"$pod\", http_response_status_code!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{k8s_pod_name=\"$pod\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{k8s_pod_name=\"$pod\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{k8s_pod_name=\"$pod\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{k8s_pod_name=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{k8s_pod_name=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{k8s_pod_name=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{k8s_pod_name=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{k8s_pod_name=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{k8s_pod_name=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"$pod\"}",
     "legendFormat": "working"
    },
    {
     "expr": "container_memory_rss{pod=\"$pod\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "container_memory_usage_bytes{pod=\"$pod\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name) (system_cpu_usage{k8s_pod_name=\"$pod\"})",
     "legendFormat": "system"
    },
    {
     "expr": "avg by (k8s_pod_name) (process_cpu_usage{k8s_pod_name=\"$pod\"})",
     "legendFormat": "process"
    },
    {
     "expr": "avg by (k8s_pod_name) (avg_over_time(process_cpu_usage{k8s_pod_name=\"$pod\"}[15m]))",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name)(system_load_average_1m{k8s_pod_name=\"$pod\"})",
     "legendFormat": "system-1m"
    },
    {
     "expr": "avg by (k8s_pod_name)(system_cpu_count{k8s_pod_name=\"$pod\"})",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name)(jvm_threads_live{k8s_pod_name=\"$pod\"})",
     "legendFormat": "live"
    },
    {
     "expr": "avg by (k8s_pod_name)(jvm_threads_daemon{k8s_pod_name=\"$pod\"})",
     "legendFormat": "daemon"
    },
    {
     "expr": "avg by (k8s_pod_name)(jvm_threads_peak{k8s_pod_name=\"$pod\"})",
     "legendFormat": "peak"
    },
    {
     "expr": "container_threads{pod=\"$pod\"}",
     "legendFormat": "container"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name, state) (jvm_threads_states{k8s_pod_name=\"$pod\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_milliseconds_sum{k8s_pod_name=\"$pod\"}[1m])) by (k8s_pod_name) / on(k8s_pod_name) system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (k8s_pod_name, level) (increase(logback_events_total{k8s_pod_name=\"$pod\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (k8s_pod_name) (process_files_open{k8s_pod_name=\"$pod\"})",
     "legendFormat": "open"
    },
    {
     "expr": "max by (k8s_pod_name) (process_files_max{k8s_pod_name=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (k8s_pod_name, id) (jvm_memory_used_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max by (k8s_pod_name, id) (jvm_memory_committed_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "max by (k8s_pod_name, id) (jvm_memory_max_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (k8s_pod_name, id) (jvm_memory_used_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max by (k8s_pod_name, id) (jvm_memory_committed_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "max by (k8s_pod_name, id) (jvm_memory_max_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_milliseconds_count{k8s_pod_name=\"$pod\"}[1m])*1000",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_milliseconds_sum{k8s_pod_name=\"$pod\"}[1m])/rate(jvm_gc_pause_milliseconds_count{k8s_pod_name=\"$pod\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (k8s_pod_name) (rate(jvm_gc_memory_allocated_bytes_total{k8s_pod_name=\"$pod\"}[1m]))",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum by (k8s_pod_name) (rate(jvm_gc_memory_promoted_bytes_total{k8s_pod_name=\"$pod\"}[1m]))",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (k8s_pod_name) (jvm_classes_loaded{k8s_pod_name=\"$pod\"})",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (k8s_pod_name) (delta(jvm_classes_loaded{k8s_pod_name=\"$pod\"}[1m]))",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "$jvm_buffer_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "repeat": "jvm_buffer_pool",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (k8s_pod_name, id) (jvm_buffer_memory_used_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_buffer_pool\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max by (k8s_pod_name, id) (jvm_buffer_total_capacity_bytes{k8s_pod_name=\"$pod\", id=~\"$jvm_buffer_pool\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "max by (k8s_pod_name, id) (jvm_buffer_count_buffers{k8s_pod_name=\"$pod\", id=~\"$jvm_buffer_pool\"})",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}