CREATE TABLE IF NOT EXISTS FORWARD_LOG (
    ID UUID PRIMARY KEY,
    LOG_DATE TIMESTAMP NOT NULL,
    POD_NAME VARCHAR(255) NOT NULL,
    TARGET_POD_NAME VARCHAR(255) NOT NULL,
    HTTP_STATUS INT NOT NULL
);
