apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-node
  labels:
    app: echo-service-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-service-node
  template:
    metadata:
      labels:
        app: echo-service-node
    spec:
      containers:
        - name: echo-service-node
          image: owahlen/echo-service-node:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: MAX_REQUESTS_PER_SOCKET
              value: "50"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: http/protobuf
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000"   # ms
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: http # set to http/dup to emit stable + legacy HTTP metrics during migration
            - name: OTEL_SERVICE_NAME
              value: echo-service-node
            - name: OTEL_SERVICE_NAMESPACE
              value: default
            # Optional: enable SDK debug logs
            # - name: OTEL_LOG_LEVEL
            #   value: debug
            # Optional: disable traces/logs if you only want metrics
            # - name: OTEL_TRACES_EXPORTER
            #   value: none
            # - name: OTEL_LOGS_EXPORTER
            #   value: none
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
