apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-node
  labels:
    app: echo-service-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-service-node
  template:
    metadata:
      labels:
        app: echo-service-node
    spec:
      containers:
        - name: echo-service-node
          image: owahlen/echo-service-node:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: MAX_REQUESTS_PER_SOCKET
              value: "50"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: http/protobuf
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000"   # ms
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: http # set to http/dup to emit stable + legacy HTTP metrics during migration
            - name: OTEL_SERVICE_NAME
              value: echo-service-node
            - name: OTEL_SERVICE_NAMESPACE
              value: default
            # Optional: enable SDK debug logs
            # - name: OTEL_LOG_LEVEL
            #   value: debug
            # Optional: disable traces/logs if you only want metrics
            # - name: OTEL_TRACES_EXPORTER
            #   value: none
            # - name: OTEL_LOGS_EXPORTER
            #   value: none
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service-node
  labels:
    app: echo-service-node
spec:
  selector:
    app: echo-service-node
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-service-node
  labels:
    app: forward-service-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-service-node
  template:
    metadata:
      labels:
        app: forward-service-node
    spec:
      containers:
        - name: forward-service-node
          image: owahlen/forward-service-node:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: FORWARD_BASE_URL
              value: http://echo-service-node:3000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: http/protobuf
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000"   # ms
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: http
            - name: OTEL_SERVICE_NAME
              value: forward-service-node
            - name: OTEL_SERVICE_NAMESPACE
              value: default
            - name: CONNECTIONS
              value: "10"
            - name: CLIENT_TTL
              value: "30000"
            - name: KEEPALIVE_TIMEOUT
              value: "4000"
            - name: KEEPALIVE_THRESHOLD
              value: "1000"
            - name: MAX_REQUESTS_PER_CLIENT
              value: "50"
            - name: PIPELINING
              value: "1"
            - name: ALLOW_H2
              value: "false"
            # Optional: enable SDK debug logs
            # - name: OTEL_LOG_LEVEL
            #   value: debug
            # Optional: disable traces/logs if you only want metrics
            # - name: OTEL_TRACES_EXPORTER
            #   value: none
            # - name: OTEL_LOGS_EXPORTER
            #   value: none
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: forward-service-node
  labels:
    app: forward-service-node
spec:
  selector:
    app: forward-service-node
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-service-webflux
  labels:
    app: forward-service-webflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-service-webflux
  template:
    metadata:
      labels:
        app: forward-service-webflux
    spec:
      containers:
        - name: forward-service-webflux
          image: owahlen/forward-service-webflux:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UseG1GC
                -XX:MaxRAMPercentage=60
                -XX:InitialRAMPercentage=60
                -XX:MaxMetaspaceSize=128m
                -XX:+ExitOnOutOfMemoryError
            - name: FORWARD_BASE_URL
              value: http://echo-service-node:3000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000ms"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000ms"   # ms
            - name: OTEL_SERVICE_NAME
              value: forward-service-webflux
            - name: OTEL_SERVICE_NAMESPACE
              value: default
            - name: CLIENT_MAX_CONNECTIONS
              value: "10"
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 800Mi
            limits:
              cpu: 1000m
              memory: 800Mi
---
apiVersion: v1
kind: Service
metadata:
  name: forward-service-webflux
  labels:
    app: forward-service-webflux
spec:
  selector:
    app: forward-service-webflux
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-service-mvc
  labels:
    app: forward-service-mvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-service-mvc
  template:
    metadata:
      labels:
        app: forward-service-mvc
    spec:
      containers:
        - name: forward-service-mvc
          image: owahlen/forward-service-mvc:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UseG1GC
                -XX:MaxRAMPercentage=60
                -XX:InitialRAMPercentage=60
                -XX:MaxMetaspaceSize=128m
                -XX:+ExitOnOutOfMemoryError
            - name: FORWARD_BASE_URL
              value: http://echo-service-node:3000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000ms"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000ms"   # ms
            - name: OTEL_SERVICE_NAME
              value: forward-service-mvc
            - name: OTEL_SERVICE_NAMESPACE
              value: default
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 800Mi
            limits:
              cpu: 1000m
              memory: 800Mi
---
apiVersion: v1
kind: Service
metadata:
  name: forward-service-mvc
  labels:
    app: forward-service-mvc
spec:
  selector:
    app: forward-service-mvc
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forward-ingress
  annotations:
    # Strip the leading "/node", "/webflux" or "/mvc" path prefix and forward the remainder
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /node(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: forward-service-node
                port:
                  number: 3000
          - path: /webflux(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: forward-service-webflux
                port:
                  number: 8080
          - path: /mvc(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: forward-service-mvc
                port:
                  number: 8080
---
# deploy with: kubectl apply -f k8s-explo.yaml
# delete with: kubectl delete -f k8s-explo.yaml
