management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

  opentelemetry:
    resource-attributes:
      service.name: ${OTEL_SERVICE_NAME:forward-service-webflux}
      service.namespace: ${OTEL_SERVICE_NAMESPACE:default}

  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
        step: ${OTEL_METRIC_EXPORT_INTERVAL:60s}
        read-timeout: ${OTEL_METRIC_EXPORT_TIMEOUT:10s}
        enabled: ${OTEL_ENABLED:false}

spring:
  application:
    name: forward-service-webflux
  r2dbc:
    url: ${POSTGRES_R2DBC_URL:r2dbc:postgresql://localhost:5432/forwarddb}
    username: ${POSTGRES_USER:app}
    password: ${POSTGRES_PASSWORD:postgres}
    pool:
      max-size: ${DB_R2DBC_MAX_POOL_SIZE:10}
      initial-size: ${DB_R2DBC_INITIAL_SIZE:0}
  flyway:
    enabled: true
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/forwarddb}
    user: ${POSTGRES_USER:app}
    password: ${POSTGRES_PASSWORD:postgres}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
