apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-service-webflux
  labels:
    app: forward-service-webflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-service-webflux
  template:
    metadata:
      labels:
        app: forward-service-webflux
    spec:
      containers:
        - name: forward-service-webflux
          image: owahlen/forward-service-webflux:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UseG1GC
                -XX:MaxRAMPercentage=60
                -XX:InitialRAMPercentage=60
                -XX:MaxMetaspaceSize=128m
                -XX:+ExitOnOutOfMemoryError
            - name: FORWARD_BASE_URL
              value: http://echo-service-node:3000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000ms"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000ms"   # ms
            - name: OTEL_SERVICE_NAME
              value: forward-service-webflux
            - name: OTEL_SERVICE_NAMESPACE
              value: default
            - name: OTEL_ENABLED
              value: "true"
            - name: CLIENT_MAX_CONNECTIONS
              value: "10"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTGRES_URL
              value: jdbc:postgresql://forward-db:5432/forwarddb
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 800Mi
            limits:
              cpu: 1000m
              memory: 800Mi
