apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-service-node
  labels:
    app: forward-service-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forward-service-node
  template:
    metadata:
      labels:
        app: forward-service-node
    spec:
      containers:
        - name: forward-service-node
          image: owahlen/forward-service-node:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: FORWARD_BASE_URL
              value: http://echo-service-node:3000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4318
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: http/protobuf
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"   # ms
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: "5000"   # ms
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: http
            - name: OTEL_SERVICE_NAME
              value: forward-service-node
            - name: OTEL_SERVICE_NAMESPACE
              value: default
            - name: CONNECTIONS
              value: "10"
            - name: CLIENT_TTL
              value: "30000"
            - name: KEEPALIVE_TIMEOUT
              value: "4000"
            - name: KEEPALIVE_THRESHOLD
              value: "1000"
            - name: MAX_REQUESTS_PER_CLIENT
              value: "50"
            - name: PIPELINING
              value: "1"
            - name: ALLOW_H2
              value: "false"
            # Optional: enable SDK debug logs
            # - name: OTEL_LOG_LEVEL
            #   value: debug
            # Optional: disable traces/logs if you only want metrics
            # - name: OTEL_TRACES_EXPORTER
            #   value: none
            # - name: OTEL_LOGS_EXPORTER
            #   value: none
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTGRES_HOST
              value: forward-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: forwarddb
            - name: POSTGRES_URL
              value: jdbc:postgresql://forward-db:5432/forwarddb
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
