apiVersion: v1
kind: Service
metadata:
  name: forward-service-node
  labels:
    app: forward-service-node
spec:
  selector:
    app: forward-service-node
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
